#! /usr/bin/perl

use File::Basename;

BEGIN {
  unshift @INC, dirname ($0);
};

use FwDebPackage;
use strict;

#---------------------------------------------------------------------
#                                main                                 
#---------------------------------------------------------------------

my $usage = "package/deb/check-for-packages: fatal: usage: $0 arch depends release\n";

my $arch = $ARGV[0] or die $usage;
my $depends = $ARGV[1] or die $usage;
my $release = $ARGV[2] or die $usage;

my ($state, $virtual) = get_state ();

print join "\n", parse_depends ($state, $arch, $depends, $release);
print "\n";
