#! /bin/sh

#---------------------------------------------------------------------
#                           chicken and egg                           
#---------------------------------------------------------------------

test -f "${FW_ROOT}/share/fw/sh/fw-find.sh" && fws="${FW_ROOT}/share/fw/sh/fw-find.sh"
test -f "fw/sh/fw-find.sh" && fws="fw/sh/fw-find.sh"
test -f "fw.local/sh/fw-find.sh" && fws="fw.local/sh/fw-find.sh"
test ! -z "$fws" || {
  echo "package/deb/tag-name: fatal: can't locate fw-find.sh" 1>&2
  exit 1
}

. "$fws"

#---------------------------------------------------------------------
#                              routines                               
#---------------------------------------------------------------------

fw_source "package/deb/tag-name" "sh/fatal.sh"

#---------------------------------------------------------------------
#                                main                                 
#---------------------------------------------------------------------

which dpkg >/dev/null 2>/dev/null || {
  echo "package/deb/tag-name: error: dpkg not installed" 1>&2
  fatal "package/deb/tag-name"
}

dpkg --listfiles "$@"
